### ISSUE TITLE
ImportError: No module named dropbox

### ISSUE THREAD

**Issue by pewee** [clark800/dropbox-restore#20]
Hi, I'm trying to run this on a mac 10.7.5, python 2.7 

`Traceback (most recent call last):`
  `File "restore.py", line 2, in <module>`
   ` import sys, os, dropbox, time`
`ImportError: No module named dropbox`

My initial thought was that I didn't have the the dropbox Python API but I checked that and:

`Requirement already satisfied (use --upgrade to upgrade): dropbox in /usr/local/lib/python2.7/site-packages`

Please not I have never coded and don't know python so if I'm just missing something extremely simple, please use STOOPID instructions so I can follow them. I never changed anything inside the restore.py I assumed all I needed was the:

`python2.7 restore.py /folderA/insideFolder 2014-09-18`

On the command line?

Thanks for any help

**Comment by Bobobrien92** [comment]
Hey I was able to circumnavigate this issue by specifying where I was installing the dropbox module.

In restore.py I changed "import sys, os, dropbox, time" to "import sys, os, imp, time".
Then in the next line I imported dropbox by adding:
dropbox = imp.load_source('dropbox', '/usr/local/lib/python2.7/site-packages/dropbox').

That seemed to fix it for me.  This assumes you have the module installed there though.  You may need to locate the exact directory path by finding your python folder.

**Comment by manifest3r** [comment]
You might have multiple versions of Python installed. You have to reconfigure the Python command to call Python 2.7 not 2,6.

If you run "Python -V", it will output the version of Python currently called with the Python command.

**Comment by clark800** [comment]
Closing because this is not an issue with this script.
