### ISSUE TITLE
cannot accept more users..

### ISSUE THREAD

**Issue by chenj16** [clark800/dropbox-restore#21]
when i run the script as, and opens the url with my login info
# python2.7 restore.py /Public 2014-10-01
1. Go to: https://www.dropbox.com/1/oauth2/authorize?response_type=code&client_id=hacwza866qep9o6
2. Click "Allow" (you might have to log in first)
3. Copy the authorization code.
   Enter the authorization code here:

i got:
"This app is in development mode and can't accept more users. Contact the app developer and ask them to use the Dropbox API App Console to apply for production status."

**Comment by pjerling** [comment]
I get the same issue - please help?

"This app is in development mode and can't accept more users. Contact the app developer and ask them to use the Dropbox API App Console to apply for production status."

**Comment by clark800** [comment]
I just reset it again, should work now. Delete the token.dat file if it exists.

**Comment by karlrg** [comment]
Same issue again: "This app is in development mode and can't accept more users. Contact the app developer and ask them to use the Dropbox API App Console to apply for production status."

Where would I find token.dat?

**Comment by clark800** [comment]
Reset. `token.dat` would be in the same directory as the script if it exists.

**Comment by karlrg** [comment]
Thanks. I'll try it again tomorrow. (It's late evening here.)

**Comment by karlrg** [comment]
Restoring everything now. Thanks again, yoir script's a lifesaver!

**Comment by karlrg** [comment]
Restoring everything now. Thanks again, yoir script's a lifesaver!

**Comment by karlrg** [comment]
Apologies for duplicate post and typo
