### ISSUE TITLE
Can't accept more users

### ISSUE THREAD

**Issue by manifest3r** [clark800/dropbox-restore#22]
when i run the script as, and opens the url with my login info

python2.7 restore.py /FILENAME 2015-14-01

Go to: https://www.dropbox.com/1/oauth2/authorize?response_type=code&client_id=hacwza866qep9o6
Click "Allow" (you might have to log in first)
Copy the authorization code. Enter the authorization code here:

i got:
"This app is in development mode and can't accept more users. Contact the app developer and ask them to use the Dropbox API App Console to apply for production status."

Can you please reset it again? Thanks!!

**Comment by clark800** [comment]
Just reset it

**Comment by manifest3r** [comment]
You are freaking amazing. You just saved my weekend! My client has literally thousand of files in their dropbox folder. I was totally dreading restoring all the files manually.
