### ISSUE TITLE
Accidentally unlinked HistoryRestore application

### ISSUE THREAD

**Issue by manifest3r** [clark800/dropbox-restore#26]
Hi,

I posted yesterday, however since then I had unlinked the HistoryRestore app. Well it turns out I am unable to re-allow the application. When I try to run the restore.py script, I get the following error:

```
[user@Server~]$ python restore.py /Tellus 2015-01-14
Restoring folder: /Folder
[401] u"The given OAuth 2 access token doesn't exist or has expired."
**Note: You must specify the path starting with "/", where "/" is the root**
of your dropbox folder. So if your dropbox directory is at "/home/user/dropbox"
and you want to restore "/home/user/dropbox/folder", the ROOTPATH is "/folder".
```

How do I reallow the the application if the Auth access token is expired?

**Comment by manifest3r** [comment]
I figured it out. I had to remove the token.dat file since the old info was in there. Thanks :)

**Comment by clark800** [comment]
This has happened before. I added a help message for this case in the optimize branch: https://github.com/clark800/dropbox-restore/tree/optimize
