### ISSUE TITLE
App not putting me through the OAuth 2 authorization flow again

### ISSUE THREAD

**Issue by jacobgerber** [clark800/dropbox-restore#29]
First, thanks SO MUCH for this script. The first time I used it about a month ago, it was magic and it perfectly restored a Dropbox folder in its entirety without a hitch.

I have been trying to use it again, however, and I keep getting denied with this error message: 

[401] u"The given OAuth 2 access token doesn't exist or has expired."

I'm not sure why my OAuth 2 token doesn't work any more (did I revoke it at some point maybe?), but according to the Dropbox documentation, I need to go back through the OAuth 2 authorization flow again. I cannot find a way to force the app to do that.

So, I either need to know how to clear out the OAuth 2 token that my system is expecting, or I need some way to force my script to put me back through the authorization flow.

If you could give me any help, that would be incredibly helpful!

**Comment by clark800** [comment]
You can delete the token.dat file found in the same directory as the script.

**Comment by jacobgerber** [comment]
Thank you so much for your help!

Jacob

--
Jacob Gerber
(Cell) 402.570.3224
jacobgerber@gmail.com
http://freedailybiblestudy.com
