### ISSUE TITLE
Files outside the retention window are deleted locally

### ISSUE THREAD

**Issue by tedski** [clark800/dropbox-restore#30]
If you pass a date outside the users' retention window (default 30 days), local files are deleted instead of restored.

**Comment by clark800** [comment]
I added a check to require that the cutoff date is within the past 30 days.

**Comment by tedski** [comment]
This will overly restrict users who pay for [Extended Version History](https://www.dropbox.com/en/help/113).  I'm not sure if there's a way to detect a user's retention window or not.

**Comment by clark800** [comment]
Yeah, but that's the best approach I could think of; I didn't see any way to check if they have extended version history through the API. Users who do have it can just delete the check from the source code.
