### ISSUE TITLE
Invalid future date check

### ISSUE THREAD

**Issue by fhscholl** [clark800/dropbox-restore#33]
Since dropbox uses UTC time for files, datetime.utcnow() should be used in the line below. For recent short term restores, the current comparison improperly states a UTC time is in the future if it is within the offset window for a negative offset. (e.g. I am in UTC -5, and was trying to restore files from one hour ago.)

 if cutoff_datetime > datetime.now():

**Comment by clark800** [comment]
Thanks, fixed.
