### ISSUE TITLE
App in development mode

### ISSUE THREAD

**Issue by Akral** [clark800/dropbox-restore#37]
Unable to authenticate with the following error:

This app is in development mode and can't accept more users. Contact the app developer and ask them to use the Dropbox API App Console to apply for production status

Is this the case or is there a different issue?

Thanks for your time

**Comment by kleuter** [comment]
![sshot-2016-03-17- 13-08-19](https://cloud.githubusercontent.com/assets/2600624/13845609/5b836a92-ec41-11e5-9a35-f4b4e51b58c8.png)

**Comment by clark800** [comment]
I reset it, it should work now.

**Comment by kleuter** [comment]
Thank you

**Comment by Akral** [comment]
Thanks
